version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=teamify
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teamify
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "33033:3306"

networks:
  app-network:
    driver: bridge
volumes:
  mysql_data: 